"""chore: allowed

Revision ID: 7b036f36a21f
Revises: e76596a4e399
Create Date: 2024-10-13 00:22:14.778678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b036f36a21f"
down_revision: Union[str, None] = "e76596a4e399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("allowed", sa.Boolean(), nullable=False))
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "allowed")
    # ### end Alembic commands ###
