"""feat: transformed_url field for photo and non-unique username for user

Revision ID: e76596a4e399
Revises: b16a529169c2
Create Date: 2024-10-12 13:01:55.870131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76596a4e399'
down_revision: Union[str, None] = 'b16a529169c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('transformed_url', sa.String(length=255), nullable=False))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('photos', 'transformed_url')
    # ### end Alembic commands ###
